# Generated by Django 4.1.1 on 2023-07-13 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('matricula', models.CharField(max_length=40)),
                ('turno', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAluno', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=120)),
                ('curso', models.CharField(max_length=120)),
                ('contato', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeModalidade', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTurma', models.CharField(blank=True, max_length=120)),
                ('vagas', models.IntegerField(default=0)),
                ('genero', models.CharField(max_length=120)),
                ('dias', models.CharField(blank=True, max_length=40)),
                ('horarioInicial', models.CharField(blank=True, max_length=10)),
                ('horarioFinal', models.CharField(blank=True, max_length=10)),
                ('turno', models.CharField(blank=True, max_length=20)),
                ('espaco', models.CharField(blank=True, max_length=120)),
                ('categoria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigsportsAPI.categoriamodalidade')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigsportsAPI.modalidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigsportsAPI.professor')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigsportsAPI.matricula')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigsportsAPI.turma')),
            ],
        ),
    ]
