# Generated by Django 4.1.1 on 2023-07-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigsportsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alunoturma',
            unique_together={('matricula', 'turma')},
        ),
    ]
