# Generated by Django 4.1.1 on 2023-07-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigsportsAPI', '0002_alter_alunoturma_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alunoturma',
            unique_together=set(),
        ),
    ]
